/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.buku.vw.kasir;

import com.buku.ctr.formKasirCtr;
import com.buku.vw.FormLogin;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author BintangDiLangit
 */
public class FormKasir extends javax.swing.JFrame {

    private formKasirCtr kasirCTR;
    public FormKasir() {
        initComponents();
        kasirCTR = new formKasirCtr(this);
    }
    public JLabel getTxt_nama() {
        return txt_nama;
    }

    public JPasswordField getTxt_pass() {
        return txt_pw;
    }

    public JLabel getTxt_tanggallahir() {
        return txt_tgllahir;
    }

    public JLabel getTxt_userid() {
        return txt_user;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lihatpass = new javax.swing.JButton();
        txt_user = new javax.swing.JLabel();
        txt_nama = new javax.swing.JLabel();
        txt_tgllahir = new javax.swing.JLabel();
        txt_pw = new javax.swing.JPasswordField();
        exit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        tabelkasir = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("LM Mono 10", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Masuk Sebagai");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 24, -1, 39));

        jLabel2.setFont(new java.awt.Font("LM Mono 10", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cashier");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 69, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UserId");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 138, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 171, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Lahir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 218, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 254, -1, -1));

        lihatpass.setBackground(new java.awt.Color(0, 0, 0));
        lihatpass.setForeground(new java.awt.Color(255, 255, 255));
        lihatpass.setText("Lihat Password");
        lihatpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatpassActionPerformed(evt);
            }
        });
        getContentPane().add(lihatpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 202, -1, -1));

        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setText("jLabel7");
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 138, -1, -1));

        txt_nama.setForeground(new java.awt.Color(255, 255, 255));
        txt_nama.setText("jLabel7");
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 171, -1, -1));

        txt_tgllahir.setForeground(new java.awt.Color(255, 255, 255));
        txt_tgllahir.setText("jLabel7");
        getContentPane().add(txt_tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 218, -1, -1));

        txt_pw.setBackground(new java.awt.Color(0, 0, 0));
        txt_pw.setForeground(new java.awt.Color(255, 255, 255));
        txt_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 156, -1));

        exit.setBackground(new java.awt.Color(153, 0, 0));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 341, -1, -1));

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 341, -1, -1));

        tabelkasir.setBackground(new java.awt.Color(0, 0, 0));
        tabelkasir.setForeground(new java.awt.Color(255, 255, 255));
        tabelkasir.setText("Tabel Kasir");
        tabelkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelkasirActionPerformed(evt);
            }
        });
        getContentPane().add(tabelkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 341, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon("/media/odading/mangoleh/Semester 3/PBO/Prak/Project UAS/tokobukubintangdilangit/img/form kasir.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lihatpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatpassActionPerformed
        kasirCTR.lihatpass();
    }//GEN-LAST:event_lihatpassActionPerformed

    private void txt_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       kasirCTR.keluar();
    }//GEN-LAST:event_exitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        FormLogin n = new FormLogin();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void tabelkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelkasirActionPerformed
        kasirCTR.tombolkasir();
    }//GEN-LAST:event_tabelkasirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton lihatpass;
    private javax.swing.JButton logout;
    private javax.swing.JButton tabelkasir;
    private javax.swing.JLabel txt_nama;
    private javax.swing.JPasswordField txt_pw;
    private javax.swing.JLabel txt_tgllahir;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
