/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.buku.vw.admin;

import com.buku.ctr.BukuCtr;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author BintangDiLangit
 */
public class Buku extends javax.swing.JFrame {
private BukuCtr bukucontroller;
    public Buku() {
        initComponents();
        bukucontroller = new BukuCtr(this);
    }

    public JTable getTabelbuku() {
        return tabelbuku;
    }

    public JTextField getTxt_harga() {
        return txt_harga;
    }

    public JTextField getTxt_jenis() {
        return txt_jenis;
    }

    public JTextField getTxt_kodebuku() {
        return txt_kodebuku;
    }

    public JTextField getTxt_nama() {
        return txt_nama;
    }

    public JTextField getTxt_stok() {
        return txt_stok;
    }

    public JButton getBtn_cari() {
        return btn_cari;
    }

    public JButton getBtn_databaru() {
        return btn_databaru;
    }

    public JButton getBtn_hapus() {
        return btn_hapus;
    }

    public JButton getBtn_ubah() {
        return btn_rubah;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kodebuku = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_jenis = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_stok = new javax.swing.JTextField();
        btn_rubah = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_databaru = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbuku = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kodebuku.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        txt_kodebuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodebukuActionPerformed(evt);
            }
        });
        getContentPane().add(txt_kodebuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 212, -1));

        txt_nama.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 212, -1));

        txt_jenis.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        getContentPane().add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 212, -1));

        txt_harga.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 212, -1));

        txt_stok.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        getContentPane().add(txt_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 212, -1));

        btn_rubah.setBackground(new java.awt.Color(0, 0, 0));
        btn_rubah.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_rubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_rubah.setText("Rubah");
        btn_rubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, -1));

        btn_cari.setBackground(new java.awt.Color(0, 0, 0));
        btn_cari.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_cari.setForeground(new java.awt.Color(255, 255, 255));
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, -1));

        btn_hapus.setBackground(new java.awt.Color(0, 0, 0));
        btn_hapus.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 124, -1));

        btn_databaru.setBackground(new java.awt.Color(0, 0, 0));
        btn_databaru.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_databaru.setForeground(new java.awt.Color(255, 255, 255));
        btn_databaru.setText("Data Baru");
        btn_databaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databaruActionPerformed(evt);
            }
        });
        getContentPane().add(btn_databaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 124, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Segarkan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 100, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, -1));

        tabelbuku.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbuku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 64, 614, 341));

        jLabel3.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stok");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon("/media/odading/mangoleh/Semester 3/PBO/Prak/Project UAS/tokobukubintangdilangit/img/bukuAdmin.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kodebukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodebukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodebukuActionPerformed

    private void btn_rubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rubahActionPerformed
        bukucontroller.tombolrubah();
        
    }//GEN-LAST:event_btn_rubahActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        bukucontroller.tombolcari();
        
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
       bukucontroller.tombolhapus();
   
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_databaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databaruActionPerformed
        bukucontroller.tomboltambah();

    }//GEN-LAST:event_btn_databaruActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        bukucontroller.komponen("segarkan");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bukucontroller.tombolKembali();
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbukuMouseClicked
        bukucontroller.kliktabel(evt);
       
    }//GEN-LAST:event_tabelbukuMouseClicked

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_databaru;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_rubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelbuku;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_kodebuku;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_stok;
    // End of variables declaration//GEN-END:variables
}
