/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.buku.vw.admin;

import com.buku.ctr.DetailCtr;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author BintangDiLangit
 */
public class DetPenjualan extends javax.swing.JFrame {
    private DetailCtr detailCtr;
    /**
     * Creates new form DetPenjualan
     */
    public DetPenjualan() {
        initComponents();
        detailCtr = new DetailCtr(this);
    }
    public JTable getTabelDetail() {
        return TabelDetail;
    }

    public JTextField getTxt_jumlah_harga() {
        return txt_jumlah_harga;
    }

    public JLabel getTxt_kodestruk() {
        return txt_kodestruk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_kodestruk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDetail = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_jumlah_harga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("LM Mono 10", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detail Struk");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Struk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 76, -1, -1));

        txt_kodestruk.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        txt_kodestruk.setForeground(new java.awt.Color(255, 255, 255));
        txt_kodestruk.setText("jLabel8");
        getContentPane().add(txt_kodestruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 76, -1, -1));

        TabelDetail.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        TabelDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelDetail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 169, 580, 297));

        jLabel3.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Penjualan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 485, -1, 30));

        txt_jumlah_harga.setBackground(new java.awt.Color(0, 0, 0));
        txt_jumlah_harga.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        txt_jumlah_harga.setForeground(new java.awt.Color(255, 255, 255));
        txt_jumlah_harga.setText("jTextField1");
        getContentPane().add(txt_jumlah_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 166, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 126, 103, -1));

        bg.setIcon(new javax.swing.ImageIcon("/media/odading/mangoleh/Semester 3/PBO/Prak/Project UAS/tokobukubintangdilangit/img/detailPenjualanAdmin.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       detailCtr.tombolkembali();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelDetail;
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_jumlah_harga;
    private javax.swing.JLabel txt_kodestruk;
    // End of variables declaration//GEN-END:variables
}
