/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.buku.vw.admin;

import com.buku.ctr.penjualanCtr;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author BintangDiLangit
 */
public class Penjualan extends javax.swing.JFrame {

    private penjualanCtr penjualanctr;
    public Penjualan() {
        initComponents();
        penjualanctr = new penjualanCtr(this);
    }
    
    public JLabel getTxt_tanggal() {
        return txt_tanggal;
    }

    public JTextField getTxt_idStruk() {
        return txt_idStruk;
    }

    public JTextField getTxt_user() {
        return txt_user;
    }
    
    public JTable getTabelPenjualan() {
        return TabelPenjualan;
    }

    public JLabel getTxt_waktu() {
        return txt_waktu;
    }

    public JButton getBtn_cari() {
        return btn_cari;
    }

    public JButton getBtn_detail() {
        return btn_detail;
    }

    public JButton getBtn_hapus() {
        return btn_hapus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPenjualan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_idStruk = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_detail = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_waktu = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("LM Mono 10", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Penjualan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 26, -1, -1));

        TabelPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPenjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, 742, 284));

        jLabel3.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Struk");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 85, -1, -1));

        btn_kembali.setBackground(new java.awt.Color(0, 0, 0));
        btn_kembali.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 221, 90, -1));

        jLabel4.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 122, -1, -1));

        jLabel5.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Waktu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 157, -1, -1));

        jLabel6.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Kasir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 198, -1, -1));

        txt_idStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idStrukActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idStruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 82, 386, -1));

        btn_cari.setBackground(new java.awt.Color(0, 0, 0));
        btn_cari.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_cari.setForeground(new java.awt.Color(255, 255, 255));
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 221, 81, -1));

        btn_hapus.setBackground(new java.awt.Color(0, 0, 0));
        btn_hapus.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 221, 81, -1));

        btn_detail.setBackground(new java.awt.Color(0, 0, 0));
        btn_detail.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        btn_detail.setForeground(new java.awt.Color(255, 255, 255));
        btn_detail.setText("Rincian");
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        getContentPane().add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 221, 345, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Segarkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 77, 107, -1));

        txt_waktu.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        txt_waktu.setForeground(new java.awt.Color(255, 255, 255));
        txt_waktu.setText("waktu");
        getContentPane().add(txt_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 157, -1, -1));

        txt_tanggal.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        txt_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        txt_tanggal.setText("Tanggal");
        getContentPane().add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 122, -1, -1));

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 192, 386, -1));

        bg.setIcon(new javax.swing.ImageIcon("/media/odading/mangoleh/Semester 3/PBO/Prak/Project UAS/tokobukubintangdilangit/img/PenjualanAdmin.png")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPenjualanMouseClicked
        penjualanctr.kliktabel(evt);
        
    }//GEN-LAST:event_TabelPenjualanMouseClicked

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        penjualanctr.kembali();
        
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void txt_idStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idStrukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idStrukActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        penjualanctr.tombolcari();
        
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        penjualanctr.tombolhapus();
       
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        penjualanctr.tombolDetail();
        
    }//GEN-LAST:event_btn_detailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        penjualanctr.komponen("segarkan");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPenjualan;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_idStruk;
    private javax.swing.JLabel txt_tanggal;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel txt_waktu;
    // End of variables declaration//GEN-END:variables
}
