/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.buku.vw;

import com.buku.ctr.ubahPassCtr;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author odading
 */
public class FormUbahPass extends javax.swing.JFrame {

    private ubahPassCtr rubahController;
    
    public FormUbahPass() {
        initComponents();
        rubahController = new ubahPassCtr(this);
    }
    
    public JPasswordField getPwOld(){
        return pwLama;
    }
    
    public JPasswordField getPwnew(){
        return pwBaru;
    }
    
    public JPasswordField getPwCon(){
        return pwKon;
    }
    
    public JLabel getTxtUser(){
        return lbl_userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_userId = new javax.swing.JLabel();
        pwLama = new javax.swing.JPasswordField();
        pwBaru = new javax.swing.JPasswordField();
        pwKon = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ubah Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 27, -1, 27));

        jLabel2.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserId");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 72, -1, -1));

        jLabel3.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password Lama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password Baru");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 147, -1, -1));

        jLabel5.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Konfirmasi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 186, -1, -1));

        lbl_userId.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        lbl_userId.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userId.setText("label_userId");
        getContentPane().add(lbl_userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 72, 175, -1));

        pwLama.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        getContentPane().add(pwLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 105, 175, -1));

        pwBaru.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        getContentPane().add(pwBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 144, 175, -1));

        pwKon.setFont(new java.awt.Font("LM Mono 10", 0, 12)); // NOI18N
        getContentPane().add(pwKon, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 183, 175, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 253, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("LM Mono 10", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Selesai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 253, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon("/media/odading/mangoleh/Semester 3/PBO/Prak/Project UAS/tokobukubintangdilangit/img/ubahpass.png")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      rubahController.kembali();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        rubahController.rubah();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_userId;
    private javax.swing.JPasswordField pwBaru;
    private javax.swing.JPasswordField pwKon;
    private javax.swing.JPasswordField pwLama;
    // End of variables declaration//GEN-END:variables
}
